version: '3'
services:
  webapp:
    image: python-webapp
    build: ./webapp
    ports:
      - "8080"
    deploy:
      replicas: 3
    depends_on:
      mysql: 
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - webapp

  mysql:
    image: mysql-webapp
    build: ./mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: "mysql -uroot -proot -e \"SHOW TABLEs LIKE 'counter'\" db"
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s